#!/bin/sh
set -e

AGENTIC_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB="$AGENTIC_ROOT/store/agentic.db"
BRAIN_DIR="${AGENTIC_BRAIN_DIR:-$HOME/SecondBrain/Second Brain}"
PROJECTS_DIR="$BRAIN_DIR/projects"

mkdir -p "$PROJECTS_DIR"

safe_name() {
  printf '%s' "$1" | tr '/' '-'
}

COMMUNITY_THRESHOLD="${BRAIN_MIRROR_COMMUNITY_THRESHOLD:-100}"

parse_community_count() {
  REPORT="$1"
  sed -n 's/^- [0-9][0-9]* nodes · [0-9][0-9]* edges · \([0-9][0-9]*\) communities.*/\1/p' "$REPORT" | head -1
}

write_graph_report_mirror() {
  SRC_REPORT="$1"
  DEST_REPORT="$2"
  PROJECT_PATH="$3"
  GRAPH_JSON="$4"

  if [ ! -f "$SRC_REPORT" ]; then
    rm -f "$DEST_REPORT"
    return 0
  fi

  COMMUNITIES="$(parse_community_count "$SRC_REPORT")"
  LARGE=0
  if [ -n "$COMMUNITIES" ] && [ "$COMMUNITIES" -ge "$COMMUNITY_THRESHOLD" ] 2>/dev/null; then
    LARGE=1
  fi

  awk -v large="$LARGE" '
    BEGIN { skip = 0 }
    /^## / {
      if ($0 ~ /^## Community Hubs/) { skip = 1; next }
      if (large && $0 ~ /^## Communities \(/) { skip = 1; next }
      skip = 0
    }
    skip { next }
    { print }
  ' "$SRC_REPORT" > "$DEST_REPORT"

  {
    echo
    echo "## Brain mirror (Obsidian-safe)"
    echo
    echo "This is a trimmed copy for the Second Brain vault. Community hub wikilinks are omitted because they create thousands of empty Obsidian nodes."
    if [ "$LARGE" = 1 ]; then
      echo "Community detail sections are omitted for large graphs ($COMMUNITIES communities)."
    fi
    echo
    echo "- Full report: \`$SRC_REPORT\`"
    echo "- Wiki index: \`$(dirname "$SRC_REPORT")/wiki/index.md\`"
    echo "- Interactive graph: \`$(dirname "$SRC_REPORT")/graph.html\`"
    echo "- Query: \`graphify query \"<question>\" --graph \"$GRAPH_JSON\"\`"
  } >> "$DEST_REPORT"
}

mirror_one() {
  NAME="$1"
  PROJECT_PATH="$2"
  SRC="$PROJECT_PATH/graphify-out"
  if [ ! -f "$SRC/graph.json" ]; then
    echo "skip: no graph for $NAME ($SRC/graph.json missing)"
    return 0
  fi
  DEST="$PROJECTS_DIR/$(safe_name "$NAME")"
  mkdir -p "$DEST"

  write_graph_report_mirror "$SRC/GRAPH_REPORT.md" "$DEST/GRAPH_REPORT.md" "$PROJECT_PATH" "$SRC/graph.json"
  rm -f "$DEST/graph.html" 2>/dev/null || true

  TODAY=$(date +%Y-%m-%d)
  {
    echo "---"
    echo "type: project-mirror"
    echo "tags: [project, graphify]"
    echo "project: \"$NAME\""
    echo "source: \"$PROJECT_PATH\""
    echo "updated: $TODAY"
    echo "---"
    echo
    echo "# $NAME (code graph)"
    echo
    echo "**Summary**: Graphify knowledge-graph mirror of \`$PROJECT_PATH\`. Generated by Agentic OS - do not hand-edit."
    echo
    [ -f "$DEST/GRAPH_REPORT.md" ] && echo "- [Graph report](GRAPH_REPORT.md) (trimmed — no community wikilinks)"
    echo "- Interactive graph (open in browser): \`$SRC/graph.html\`"
    echo "- Query the live graph: \`graphify query \"<question>\" --graph \"$SRC/graph.json\"\`"
    echo "- Dev wiki (hand-curated): \`wiki/projects/$(safe_name "$NAME")/\`"
  } > "$DEST/index.md"

  echo "mirrored: $NAME -> $DEST"
}

rebuild_catalog() {
  TODAY=$(date +%Y-%m-%d)
  {
    echo "---"
    echo "type: index"
    echo "updated: $TODAY"
    echo "---"
    echo
    echo "# Projects (Graphify mirrors)"
    echo
    echo "Code knowledge-graph mirrors of registered Agentic OS projects. Generated - do not hand-edit."
    echo
    for d in "$PROJECTS_DIR"/*/; do
      [ -d "$d" ] || continue
      base=$(basename "$d")
      echo "- [[$base/index|$base]]"
    done
  } > "$PROJECTS_DIR/index.md"
}

if [ -n "$1" ] && [ -n "$2" ]; then
  mirror_one "$1" "$2"
  exit 0
fi

if [ ! -f "$DB" ]; then
  echo "no project db at $DB"
  exit 0
fi

sqlite3 "$DB" "SELECT name || '|' || path FROM projects;" 2>/dev/null | while IFS='|' read -r NAME PROJECT_PATH; do
  [ -n "$NAME" ] || continue
  mirror_one "$NAME" "$PROJECT_PATH"
done

rebuild_catalog
echo "brain mirror complete -> $PROJECTS_DIR"
